/**
 * GAIA Protocol Commands for Equalizer Control
 * Based on Qualcomm GAIA Control Android SDK 3.4.0.52
 */

export const GAIA_COMMANDS = {
  // Equalizer Control Commands
  COMMAND_SET_EQ_CONTROL: 0x0214,
  COMMAND_GET_EQ_CONTROL: 0x0294,
  COMMAND_SWITCH_EQ_CONTROL: 0x0217,
  COMMAND_SET_EQ_PARAMETER: 0x021a,
  COMMAND_GET_EQ_PARAMETER: 0x029a,
  COMMAND_SET_EQ_GROUP_PARAMETER: 0x021b,
  COMMAND_GET_EQ_GROUP_PARAMETER: 0x029b,
  COMMAND_SET_USER_EQ_CONTROL: 0x0220,
  COMMAND_GET_USER_EQ_CONTROL: 0x02a0,
  COMMAND_TOGGLE_USER_EQ_CONTROL: 0x0221,
  COMMAND_SET_SPEAKER_EQ_CONTROL: 0x0222,
  COMMAND_GET_SPEAKER_EQ_CONTROL: 0x02a2,
  COMMAND_TOGGLE_SPEAKER_EQ_CONTROL: 0x0223,

  // Bass Boost and 3D Enhancement
  COMMAND_SET_BASS_BOOST_CONTROL: 0x0215,
  COMMAND_GET_BASS_BOOST_CONTROL: 0x0295,
  COMMAND_TOGGLE_BASS_BOOST_CONTROL: 0x0218,
  COMMAND_SET_3D_ENHANCEMENT_CONTROL: 0x0216,
  COMMAND_GET_3D_ENHANCEMENT_CONTROL: 0x0296,
  COMMAND_TOGGLE_3D_ENHANCEMENT_CONTROL: 0x0219,
};

export const GAIA_STATUS = {
  SUCCESS: 0x00,
  NOT_SUPPORTED: 0x01,
  NOT_AUTHENTICATED: 0x02,
  INSUFFICIENT_RESOURCES: 0x03,
  AUTHENTICATING: 0x04,
  INVALID_PARAMETER: 0x05,
  INCORRECT_STATE: 0x06,
  IN_PROGRESS: 0x07,
};

export const GAIA_VENDOR = {
  NONE: 0x7ffe,
  QUALCOMM: 0x000a,
};

export const GAIA_TRANSPORT = {
  BLE: 0x00,
  BR_EDR: 0x01,
};

// Equalizer specific constants
export const EQUALIZER_CONSTANTS = {
  NUMBER_OF_PRESETS: 3,
  CUSTOMIZABLE_PRESET: 2,
  NUMBER_OF_BANDS: 5,
  GENERAL_BAND: 0x00,
  PARAMETER_MASTER_GAIN: 0x01,
  EQ_PARAMETER_FIRST_BYTE: 0x01,
  GET_EQ_PARAMETER_PAYLOAD_LENGTH: 5,
  SET_EQ_PARAMETER_PAYLOAD_LENGTH: 5,
};

// Parameter types for equalizer
export const PARAMETER_TYPES = {
  FILTER: 0,
  FREQUENCY: 1,
  GAIN: 2,
  QUALITY: 3,
};

// Filter types
export const FILTER_TYPES = {
  BYPASS: 0,
  LOW_PASS_1: 1,
  HIGH_PASS_1: 2,
  ALL_PASS_1: 3,
  LOW_SHELF_1: 4,
  HIGH_SHELF_1: 5,
  TILT_1: 6,
  LOW_PASS_2: 7,
  HIGH_PASS_2: 8,
  ALL_PASS_2: 9,
  LOW_SHELF_2: 10,
  HIGH_SHELF_2: 11,
  TILT_2: 12,
  PARAMETRIC_EQUALIZER: 13,
};
